# asses the history of runs

In [5]:
import sys
print(sys.executable)


import pandas as pd

/home/kandrych/venvs/obriy311/bin/python

In [6]:
import sys, subprocess, textwrap, os

print("python:", sys.executable)
print("PYTHONPATH:", os.environ.get("PYTHONPATH"))

print("\n--- pip show matplotlib (kernel) ---")
try:
    out = subprocess.check_output([sys.executable, "-m", "pip", "show", "matplotlib"], text=True)
    print(out if out.strip() else "pip: matplotlib NOT found")
except Exception as e:
    print("pip failed:", e)

print("\n--- sys.path contains /apps/modules? ---")
print(any("/apps/modules/software" in p for p in sys.path))

python: /home/kandrych/venvs/obriy311/bin/python
PYTHONPATH: None

--- pip show matplotlib (kernel) ---
pip failed: Command '['/home/kandrych/venvs/obriy311/bin/python', '-m', 'pip', 'show', 'matplotlib']' returned non-zero exit status 1.

--- sys.path contains /apps/modules? ---
True

WARNING: Package(s) not found: matplotlib

In [2]:
df=pd.read_csv("/fred/oz061/kandrych/smac/test_new_features/after_optimisation/trials.csv")
results_dir="/fred/oz061/kandrych/smac/test_new_features/after_optimisation/"
df

,alpha_viscosity,distance_pc,zone_1_Rc,zone_1_dust_mass,zone_1_flaring_exp,zone_1_gamma_exp,zone_1_gas_to_dust,zone_1_scale_height,zone_1_species_1_amin,zone_1_species_1_porosity,zone_1_species_1_volume_fraction,zone_1_surface_density_exp,config_id,seed,budget,cost,time,status
0,0.020699,1220.0,47.011930,0.001,1.401312,-1.233564,100.0,1.063392,0.498057,0.397948,0.8,1.166834,8,1850920004,2.0,228.655047,243.696087,1
1,0.003739,1220.0,33.168058,0.001,1.126624,0.638861,50.0,1.540537,0.886917,0.102527,0.8,0.898612,10,1850920004,2.0,399.366143,226.657204,1
2,0.016318,1220.0,42.159667,0.002,1.534936,0.682955,50.0,1.538179,0.711474,0.245565,0.7,-0.530747,6,1850920004,2.0,498.508237,291.269012,1
3,0.024856,1220.0,13.628440,0.001,1.035854,1.301495,100.0,1.741443,0.779095,0.140095,0.8,1.366487,7,1850920004,2.0,1251.904766,292.457130,1
4,0.049401,1220.0,19.169474,0.001,1.165292,-0.870436,200.0,0.984467,0.156124,0.466504,0.7,0.532293,9,1850920004,2.0,1418.135221,269.203455,1
5,0.049401,1220.0,15.302166,0.001,1.200340,-0.870436,50.0,0.984467,0.156124,0.437815,0.7,0.532293,5,1850920004,2.0,2111.069867,353.701867,1
6,0.001386,1220.0,17.563919,0.001,1.105279,1.327689,50.0,1.303313,0.170684,0.464319,0.7,0.753188,4,1850920004,2.0,2480.339145,346.510484,1
7,0.000529,1220.0,37.476528,0.002,1.101356,-1.887291,100.0,1.035736,0.532745,0.783742,0.7,-0.225440,1,1850920004,2.0,2871.105400,384.995210,1
8,0.000590,1220.0,28.526374,0.001,1.192473,-0.120642,50.0,0.964701,0.382477,0.589113,0.8,-0.179347,3,1850920004,2.0,2922.184202,341.109890,1
9,0.000348,1220.0,12.093784,0.001,1.053690,1.863932,50.0,1.650519,0.375901,0.688989,0.8,0.417907,2,1850920004,2.0,5050.748165,410.243929,1

### Best configs table (at max budget)

In [3]:
top = df[df["budget"] == df["budget"].max()].nsmallest(5, "cost")
print("Top 5 max budget trials:")
top
#top.to_csv(results_dir / "top5_maxbudget.csv", index=False)

Top 5 max budget trials:

,alpha_viscosity,distance_pc,zone_1_Rc,zone_1_dust_mass,zone_1_flaring_exp,zone_1_gamma_exp,zone_1_gas_to_dust,zone_1_scale_height,zone_1_species_1_amin,zone_1_species_1_porosity,zone_1_species_1_volume_fraction,zone_1_surface_density_exp,config_id,seed,budget,cost,time,status
0,0.020699,1220.0,47.011930,0.001,1.401312,-1.233564,100.0,1.063392,0.498057,0.397948,0.8,1.166834,8,1850920004,2.0,228.655047,243.696087,1
1,0.003739,1220.0,33.168058,0.001,1.126624,0.638861,50.0,1.540537,0.886917,0.102527,0.8,0.898612,10,1850920004,2.0,399.366143,226.657204,1
2,0.016318,1220.0,42.159667,0.002,1.534936,0.682955,50.0,1.538179,0.711474,0.245565,0.7,-0.530747,6,1850920004,2.0,498.508237,291.269012,1
3,0.024856,1220.0,13.628440,0.001,1.035854,1.301495,100.0,1.741443,0.779095,0.140095,0.8,1.366487,7,1850920004,2.0,1251.904766,292.457130,1
4,0.049401,1220.0,19.169474,0.001,1.165292,-0.870436,200.0,0.984467,0.156124,0.466504,0.7,0.532293,9,1850920004,2.0,1418.135221,269.203455,1

### Pairwise sanity checks (parameter vs cost)

In [1]:
import matplotlib.pyplot as plt

for p in ["inc_deg", "rin_au", "dust_mass"]:  # rename to your actual names
    if p in df.columns:
        plt.figure()
        plt.scatter(df[p], df["cost"])
        plt.xlabel(p); plt.ylabel("cost")
        plt.yscale("log")  # often helpful
        plt.tight_layout()
        plt.show()
        #plt.savefig(results_dir / f"scatter_{p}.png", dpi=150)
        plt.close()

ModuleNotFoundError: No module named 'matplotlib'

### Slice by budget (does the story change with fidelity?)

In [ ]:
df.groupby("budget")["cost"].describe().to_csv(results_dir / "cost_by_budget.csv")

### Parameter importance (fast, practical)

In [ ]:
def binned_medians(df, param, bins=10):
    s = df[[param, "cost"]].dropna()
    s["bin"] = pd.qcut(s[param], q=bins, duplicates="drop")
    return s.groupby("bin")["cost"].median().sort_values()

for p in ["inc_deg", "rin_au", "dust_mass"]:
    if p in df.columns:
        bm = binned_medians(df[df["budget"] == df["budget"].max()], p)
        bm.to_csv(results_dir / f"binned_median_{p}.csv")

### Clustering of “good” solutions (degeneracies)

In [ ]:
good = df[df["budget"] == df["budget"].max()].nsmallest(50, "cost")
good.describe().to_csv(results_dir / "good50_summary.csv")

### Plot

In [ ]:
curve = df.groupby(["config_id", "budget"])["cost"].min().reset_index()
curve.to_csv(results_dir / "learning_curves.csv", index=False)